


name: app_client
description: 'A new Flutter project. Created by Slidy'

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.6+3
  geolocator: ^5.3.1
  flutter_lottie: ^0.2.0
  lottie: ^0.3.2
  google_maps_flutter: ^0.5.25+1
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+2
  flutter_modular: ^0.5.6
  flutter:
    sdk: flutter



dev_dependencies:
  effective_dart: ^1.2.1
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/map/dark_map_style.txt

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs